NETTY-415 ChannelFuture.setFailure() not called when exception thrown handling Channel.close()

* Made sure the ChannelFuture associated with a downstream event is marked as failure when an exception is raised before it reaches at ChannelSink.
