[+++ b/spring-test/src/main/java/org/springframework/test/web/client/AbstractRequestExpectationManager.java, +			try {, +				return validateRequestInternal(request);, +			}, +			finally {, +			}, +++ b/spring-test/src/main/java/org/springframework/test/web/client/AbstractRequestExpectationManager.java, +			try {, +				return validateRequestInternal(request);, +			}, +			finally {, +			}, +++ b/spring-test/src/test/java/org/springframework/test/web/client/SimpleRequestExpectationManagerTests.java, +import java.net.SocketException;, +import static org.springframework.test.util.AssertionErrors.fail;, +	@Test  // SPR-16132, +	public void sequentialRequestsWithFirstFailing() throws Exception {, +		this.manager.expectRequest(once(), requestTo("/foo")).andExpect(method(GET)), +				.andRespond(request -> { throw new SocketException("pseudo network error"); });, +		this.manager.expectRequest(once(), requestTo("/handle-error")).andExpect(method(POST)).andRespond(withSuccess());, +, +		try {, +			this.manager.validateRequest(createRequest(GET, "/foo"));, +			fail("expected exception");, +		}, +		catch (SocketException e) {, +			//expected, +		}, +		this.manager.validateRequest(createRequest(POST, "/handle-error"));, +		this.manager.verify();, +	}, +]