Merge pull request #962 from aam/master

Fix comment to make it clear that target.cancel() has to be called when exception is thrown.